### PR TITLE
Updates to introduction and placeholders for challenges and solution design

### PR DESCRIPTION
**Pull request by codepossible**
## Primary Changes
 - Updated introductory README file which includes the business use case.
 - Added placeholder for challenges and solution design.

### CODE REVIEW

**Review by davidkpiano — APPROVED** [review]

**Comment by davidkpiano** [comment]
Make sure to set your `user.email` to prevent anonymous commits: https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

```bash
git config --global user.email "email@example.com"
```

**Comment by codepossible** [comment]
Thank you for your review - @davidkpiano. Changes to local git config made.

**Review by ianphil — APPROVED** [review]
This looks like a great skeleton for us to build on. I think it will cover the needed information to get people started. Great work! 🚢 it

**Comment by codepossible** [comment]
Thank you @ianphil

**Pull request merged**
